<div class="ch-container">
    <div class="row">
        <div class="box col-md-12">
            <div class="box-inner">
                <div class="box-header well" data-original-title="">
                    <h2><i class="glyphicon glyphicon-user"></i>Lista clientes</h2>

                    <div class="box-icon">
                        <a href="#" class="btn btn-minimize btn-round btn-default"><i
                                class="glyphicon glyphicon-chevron-up"></i></a>
                        <a href="#" class="btn btn-close btn-round btn-default"><i
                                class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <?php
                        $obje = ControllerMain::makeObjects("Clientes", 1);
                        $obje->selectClientes();
                    ?>
                </div>
            </div>
        </div>
        <!--/span-->

    </div><!--/row-->

</div><!--/.fluid-container--><div class="ch-container">
   