<div class="ch-container">
    <div class="row">
        <!--AGREGAR SECCIONES-->
           <?php require_once (VISTAS.'formAgregarSeccion.phtml');?> 
        <!-- AGREGAR SECCIONES -->
    </div>
    <div class="row">
        <div class="box col-md-12">
            <div class="box-inner">
                <div class="box-header well" data-original-title="">
                    <h2><i class="glyphicon glyphicon-tag"></i> Editar actual</h2>
                    <div class="box-icon">
                        <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                        <a href="#" class="btn btn-minimize btn-round btn-default"><i class="glyphicon glyphicon-chevron-up"></i></a>
                        <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                    </div>
                </div>
                <div class="box-content">
                    <?php
                        $objeContacto = ControllerMain::makeObjects("Secciones",1);
                        $objeContacto->secciones();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
