</div>



</div><!--/.fluid-container-->

<!-- external javascript -->

<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>bootstrap/dist/js/bootstrap.min.js"></script>

<!-- library for cookie management -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.cookie.js"></script>
<!-- calender plugin -->
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>moment/min/moment.min.js"></script>
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>fullcalendar/dist/fullcalendar.min.js"></script>
<!-- data table plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.dataTables.min.js"></script>

<!-- select or dropdown enhancer -->
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>chosen/chosen.jquery.min.js"></script>
<!-- plugin for gallery image view -->
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>colorbox/jquery.colorbox-min.js"></script>
<!-- notification plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.noty.js"></script>
<!-- library for making tables responsive -->
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>responsive-tables/responsive-tables.js"></script>
<!-- tour plugin -->
<script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>bootstrap-tour/build/js/bootstrap-tour.min.js"></script>
<!-- star rating plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>charisma.js"></script>


</body>
</html>
 <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
      
        <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <div class="modal-footer">
          <button type="button" class="btn btn-default close-btn" data-dismiss="modal">Close</button>
        </div>  
        </div>
        <div class="modal-body">
          <p>Some text in the modal.</p>
        </div>
        
      </div>
      
    </div>
  </div>
  