<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        ===
        This comment should NOT be removed.

        Charisma v2.0.0

        Copyright 2012-2014 Muhammad Usman
        Licensed under the Apache License v2.0
        http://www.apache.org/licenses/LICENSE-2.0

        http://usman.it
        http://twitter.com/halalit_usman
        ===
    -->
    <meta charset="utf-8">
    <title>Administrador Heppi mercado saluble</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.">
    <meta name="author" content="Muhammad Usman">

    <!-- The styles -->
    <link  href="<?php echo RECURSOS;?>css<?php echo DS; ?>bootstrap-cerulean.min.css" rel="stylesheet" id="bs-_css" />

    <link href="<?php echo RECURSOS;?>css<?php echo DS; ?>charisma-app.css" rel="stylesheet">
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>fullcalendar/dist/fullcalendar.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>chosen/chosen.min.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>colorbox/example3/colorbox.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>responsive-tables/responsive-tables.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>jquery.noty.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>noty_theme_default.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>elfinder.min.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>elfinder.theme.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>uploadify.css' rel='stylesheet'>
    <link href='<?php echo RECURSOS;?>css<?php echo DS; ?>animate.min.css' rel='stylesheet'>
  
    <!-- jQuery -->
    <script src="<?php echo RECURSOS;?>bower_components<?php echo DS; ?>jquery/jquery.min.js"></script>
     <!-- Libreria de funciones javascritp php -->
    <script src="<?php echo RECURSOS;?>js<?php echo DS; ?>libreriaFunciones.js"></script>
    <!--Archivo validar-->
    <script src="<?php echo RECURSOS;?>js<?php echo DS; ?>funciones.validacion.js"></script>
    <!--Archivo main js-->
    <script src="<?php echo RECURSOS;?>js<?php echo DS; ?>main.js"></script>
    
    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

 

</head>

<body>
<div class="ch-container">
    <div class="row" style ="margin-top: 10%;">
        
    <div class="row">
        <div class="col-md-12 center login-header">

            <img src ="http://www.mercadoheppi.com/views/template/assets/img/heppi-market.png"/>
        </div>
        <!--/span-->
    </div><!--/row-->

    <div class="row">
        <div class="well col-md-5 center login-box">
            <div class="alert alert-info">
               Por favor ingresa tu usuario y contraseña
            </div>
            <form class="form-horizontal" id ="form-login">
                <fieldset>
                    <div class="input-group input-group-lg">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user orange"></i></span>
                        <input type="text" class="form-control" name ="usuario" placeholder="Usuario" id ="usuario">
                    </div>
                    <div class="clearfix"></div><br>

                    <div class="input-group input-group-lg">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock orange"></i></span>
                        <input type="password" name ="password"id ="password" class="form-control" placeholder="Contraseña">
                    </div>
                    <div class="clearfix"></div>
                  
                    <p class="center col-md-5">
                        <button type="submit" class="btn btn-primary">Entrar</button>
                    </p>
                </fieldset>
            </form>
        </div>
        <!--/span-->
    </div><!--/row-->
</div><!--/fluid-row-->

</div><!--/.fluid-container-->

<!-- external javascript -->

<script src='<?php echo RECURSOS;?>bower_components<?php echo DS;?>bootstrap/dist/js/bootstrap.min.js'></script>

<!-- library for cookie management -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.cookie.js"></script>
<!-- calender plugin -->
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>moment/min/moment.min.js'></script>
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>fullcalendar/dist/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.dataTables.min.js'></script>

<!-- select or dropdown enhancer -->
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>chosen/chosen.jquery.min.js'></script>
<!-- plugin for gallery image view -->
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>colorbox/jquery.colorbox-min.js'></script>
<!-- notification plugin -->
<script src='<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.noty.js'></script>
<!-- library for making tables responsive -->
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>responsive-tables/responsive-tables.js'></script>
<!-- tour plugin -->
<script src='<?php echo RECURSOS;?>bower_components<?php echo DS; ?>bootstrap-tour/build/js/bootstrap-tour.min.js'></script>
<!-- star rating plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>charisma.js"></script>


</body>
</html>
