<style type="text/css">
    #main-emboltura {
        position: relative;
        top: 139px;
    }
</style>

<script src="<?php echo RECURSOS;?>js<?php echo DS; ?>jquery.validar.js" type="text/javascript"></script>
<section id="main-emboltura">
<section class ="center-body">
    <article id ="idproducto" lan ="<?php echo $lang;?>">
        <h2 class ="titulos-heppi">MI CUENTA HEPPI</h2> <br />
    </article>
    <article>
         <form id ="form-registro" class="forms">
             <p style="text-align:center">La información ingresada en este formulario es de vital importacia, es nuestra fuente para ofrecerte un excelente servicio</p><br />
            <div class ="columna inline">
               <div class ="rows">
                   <span class ="label-form"><label>Nombre <span class ="required">*</span></label><input placeholder="Nombre" class ="validar" type ="text" name ="txtnombre" id ="txtnombre"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Apellidos <span class ="required">*</span></label><input placeholder="Apellido"   class ="validar" type ="text" name ="txtapellidos" id ="txtapellidos"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Usuario <span class ="required">*</span></label><input placeholder="Usuario"  class ="validar" type ="text" name ="txtusuario" id ="txtusuario"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Contraseña <span class ="required">*</span></label><input placeholder="Contraseña"  class ="validar" type ="password" name ="txtconstra" id ="txtconstra"/></span>
               </div>
               <div class ="rows">
                   <span class ="label-form"><label>Tipo de documento <span class ="required">*</span></label>
                       <select  class ="validar" name ="slttipodocumento" id ="slttipodocumento">
                           <?php echo $this->_objMain->cargarTipodedocumento($lang); ?>
                       </select>
                   </span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Nro documento <span class ="required">*</span></label><input placeholder="Nro de documento" validacion="id"  class ="validar" type ="text" name ="txtndocumento" id ="txtndocumento"/></span>
                </div>
            </div>
            <div class ="columna inline">
                <div class ="rows">
                    <span class ="label-form"><label>Teléfono <span class ="required">*</span></label><input placeholder="Telefono" validacion="tel"  class ="validar"type ="text" name ="txttelefono" id ="txttelefono"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Correo <span class ="required">*</span></label><input placeholder="Correo" class ="validar" type ="email" name ="txtcorreo" id ="txtcorreo"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Pais <span class ="required">*</span></label><input placeholder="Pais"  class ="validar" type ="text" name ="txtpais" id ="txtpais" value ="Colombia"/></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Departamento <span class ="required">*</span></label><input placeholder="Departamento" class ="validar" type ="text" name ="txtdepartemento" id ="txtdepartemento" /></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Ciudad <span class ="required">*</span></label><input placeholder="Ciudad" class ="validar" type ="text" name ="txtciudad" id ="txtciudad" /></span>
                </div>
                <div class ="rows">
                    <span class ="label-form"><label>Dirección residencia <span class ="required">*</span></label><input placeholder="Dirección residencial" class ="validar" type ="text" name ="txtdireccion" id ="txtdireccion"/></span>
                </div>
            </div>
             <div class ="content-button">
              <br />
              <input   id ="btn-enviar-registro" type="button" class="botones-carro" value ="<?php echo $this->translate("Registrarse",$lang);?>"/></div>
        </form>
    </article>
</section>
     
                
                
                
                
               
                
                
                