<section class ="center-body">  
<article>
        <h2 class ="titulos-rigo">Rigo<span class="color-rosa">News</span></h2>
        <?php ControllerMain::makeObjects("Noticias",1) ?>
       
    </article> 
<section id ="content-noticias" >
        <article class="noticias-items inline" >
            <div class ="encabezado-noticias">
                <img  class ="inline" src="public/noticias/clavado-rigo.jpg" alt ="rigo" title="rigo" />
                <h3 class ="titulo-noticia inline">“Que clavado <br /> parce” <br />Orlando<br /> Duque</h3>
            </div>
            <div class ="informacion-noticia ">
                <p> Que clavado parce! Con ganas de estar en Cartagena compartiendo con ud. @orlandoduque
                <br /><br />
                pic.twitter.com/kPvr4T60sm — Rigoberto Urán ЯU (@UranRigoberto) abril 25, 2015
                </p>
            </div>
            <div style="text-align: right;"><a href ="#" class="boton-negro">Ver más</a></div>
        </article>
        <article class="noticias-items inline" >
            <div class ="encabezado-noticias">
                <img  class ="inline" src="public/noticias/rigo.jpg" alt ="rigo" title="rigo" />
                <h3 class ="titulo-noticia inline">“Vamos
                    por buen
                    camino”
                    Rigoberto
                    Urán</h3>
            </div>
            <div class ="informacion-noticia ">
                <p>El doble subcampeón del Giro de Italia regresa a Colombia, pensando en el Giro de Italia. Rigoberto Urán (Etixx-Quick Step) ha finalizado quinto la Volta a Catalunya, a 18” del vencedor final Richie Porte (Team Sky), después de ser séptimo en la última etapa en…
                </p>
            </div>
            <div style="text-align: right;"><a href ="#" class="boton-negro">Ver más</a></div>
        </article>
        <article class="noticias-items inline" >
            <div class ="encabezado-noticias">
                <img  class ="inline" src="public/noticias/rigo-bici-uno.jpg" alt ="rigo" title="rigo" />
                <h3 class ="titulo-noticia inline">“Que clavado <br /> parce” <br />Orlando<br /> Duque</h3>
            </div>
            <div class ="informacion-noticia ">
                <p> Que clavado parce! Con ganas de estar en Cartagena compartiendo con ud. @orlandoduque
                <br /><br />
                pic.twitter.com/kPvr4T60sm — Rigoberto Urán ЯU (@UranRigoberto) abril 25, 2015
                </p>
            </div>
            <div style="text-align: right;"><a href ="#" class="boton-negro">Ver más</a></div>
        </article>
        <article class="noticias-items inline" >
            <div class ="encabezado-noticias">
                <img  class ="inline" src="public/noticias/rigo-bici-dos.jpg" alt ="rigo" title="rigo" />
                <h3 class ="titulo-noticia inline">“Que clavado <br /> parce” <br />Orlando<br /> Duque</h3>
            </div>
            <div class ="informacion-noticia ">
                <p> Que clavado parce! Con ganas de estar en Cartagena compartiendo con ud. @orlandoduque
                <br /><br />
                pic.twitter.com/kPvr4T60sm — Rigoberto Urán ЯU (@UranRigoberto) abril 25, 2015
                </p>
            </div>
            <div style="text-align: right;"><a href ="#" class="boton-negro">Ver más</a></div>
        </article>
    </section>