<style>
    #main-section{
        background: url(<?php echo RECURSOS; ?>img/profile-rigo-uran.jpg);
        background-size: cover;
    }
</style>
<section class ="center-body" id="profile-rigo-uran">
    <section id ="contenedor-historia" lan ="<?php echo $lang; ?>">

        <h2 class ="titulos-rigo">Rigo<span class="color-rosa blanco"><?php echo "Urán"; //$this->translate("Tienda",$lang); ?></span></h2>
        <article  id="info-rigo-historia">
            El 26 de enero de 1987, en Urrao, un pequeño poblado colombiano ubicado en el departamento de Antioquia, 
            nació Rigoberto Urán Urán. En esa zona conocida como el Páramo del Sol vivió su infancia en un ambiente familiar, 
            donde siempre contó con el apoyo de sus padres y su hermana. En esos tiempos, el pequeño “Rigo”, quien era un estudiante rebelde, 
            siempre se destacó por su inteligencia en las aulas del Liceo Jorge Iván Cadavid, donde mostró su gusto particular por el trabajo duro.<br /><br />

            El inicio de su carrera fue tan rápido como el ritmo de su pedaleo, su padre y mentor, lo inscribió en una carrera organizada por una escuela 
            de ciclismo local con muy pocos días de preparación y el día de su primera competencia ciclística le tocó correr  con una bicicleta corriente, 
            pero Rigoberto en medio de su humildad demostró la fuerza de su espíritu y de sus piernas saliendo ganador. <br /><br />

            El legado de su padre fue valorado por él como un tesoro, la constancia y disciplina que requiere el deporte reemplazaron el gusto que desde pequeño 
            Rigoberto tenía por el trabajo, y a sus catorce años, reveló que tenía madera para el deporte, empezó a montar bicicleta y entrenar en las colinas de su pueblo. 
            Desde ese momento las cosas se empezaron a dar y comenzó el ascenso en su carrera deportiva.

            Tras crecer como deportista en equipos antioqueños y competir a nivel nacional pisó suelo europeo para competir y para quedarse. Su carrera como 
            profesional ya era un gran suceso. Por su corta edad y grandes habilidades entró en el entorno del ciclismo de élite que tiene lugar en el Viejo Continente.

            Su evolución como deportista fue sorprendente, apenas tenía 19 años cuando dejó su carrera de ciclista juvenil para convertirse en profesional 
            y competir al máximo nivel, situación que en el mundo del ciclismo es relevante, 
            ya que lo más común es que deportistas  de esta especialidad continúen en categoría juvenil hasta los 24 años.<br /><br />

            En sus inicios en el ciclismo profesional, “el Riguito” como le dice su madre Aracely, entró a hacer parte del equipo Tenax junto a su compatriota Marlon Pérez.
            Equipo que no estaba dentro de la élite de los grupos europeos llenos de estrellas, pero le dio la oportunidad de mostrarse.<br /><br />

            En el año 2007, el equipo Unibet perteneciente a la categoría ProTour, conociendo las capacidades del pedalista antioqueño decidió hacerse cargo del pago de su cláusula de recisión y lo vinculó para la temporada. Urán respondió al voto de confianza con sus capacidades, liderando la Euskal Bizikleta de Abadiño, esfuerzo que se vio afectado por las condiciones meteorológicas pero más adelante en la misma temporada, ganó una etapa de la Vuelta a Suiza.

            Fue en esta etapa donde se vio obligado a enfrentar uno de los desafíos más complejos que le ha planteado el deporte. 
            Sucedió en una carrera en Alemania, se encontraba desplazándose a toda velocidad y cayó estrepitosamente sobre una roca, lo que le causó una fractura en sus codos, muñeca izquierda y clavícula, incapacitándolo alrededor de seis meses.

            Desde la recuperación de su accidente, Rigoberto Urán se ha venido consolidando como la revelación dentro del ciclismo, 
            al año siguiente pasó al Caisse d Epargne, donde corrió por tres años con excelentes resultados y adquirió la experiencia suficiente para estar entre los mejores del ciclismo europeo. El 28 de septiembre del 2010 se oficializo la entrada de Rigo al team Sky, disputando en este por tres años con excelente desempeño, posesionando de nuevo el cilismo colombiano en lo más alto y dando inicio a su vez a una nueva generación de “escarabajos”.

            En 2012 ganó una etapa de la Volta a Cataluña, fue líder de los jóvenes en el Giro de Italia y remató con una medalla olímpica en Londres, 
            entrando al selecto grupo de deportistas colombianos que han obtenido preseas en las olimpiadas.<br /><br />

            Con la medalla de plata en los olímpicos de Londres 2012, Rigoberto habló de los ciclistas colombianos en su momento: “íbamos bien preparados pero no teníamos 
            como ganar porque era un circuito que no nos convenía a nosotros, al final fue una sorpresa” y eso era cierto, Urán es reconocido mundialmente por ser uno de los 
            mejores escaladores pero su medalla la ganó en ciclismo de ruta, un circuito plano que en teoría no le favorecía.<br /><br />

            También en 2012 Urán mostró su talento en el Giro de Italia, cuando Bradley Wiggins, líder del team Sky se vio obligado a retirarse. 
            Rigoberto Urán asumió la capitanía del equipo, terminando la competencia a 4 minutos y 43 segundos de Vicenzo Nibali, lo que le permitió ocupar un 
            meritorio y épico segundo puesto, otra emoción más para él y para los colombianos.<br /><br />

            De cara al futuro, Rigoberto Urán se posiciona como una de las promesas del ciclismo mundial, para 2014 conformará 
            un “Dream Team” en el Omega Pharma – Quickstep,  donde la comunidad del ciclismo mundial solo le augura triunfos.<br /><br />   
        </article>
    </section>
</section>